export enum EstadoAsistenciaExtra {
  PUNTUAL_EXTRA = 'PUNTUAL-EXTRA',
  TARDANZA_EXTRA = 'TARDANZA-EXTRA',
  JUSTIFICADO_EXTRA = 'JUSTIFICADO-EXTRA',
  ANULADO_EXTRA = 'ANULADO-EXTRA',
  AUSENTE_EXTRA = 'AUSENTE-EXTRA',
}
